## text data encoding

In [55]:
#imports
from IPython.display import display, Markdown #just to display markdown

# keras imports
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Flatten, Dense

# visualiaztion imports
%matplotlib inline
import matplotlib.pyplot as plt

# general imports
import numpy as np  #for vector operation
import string   # provides strings variations for character embedding
import os

In [56]:
display(Markdown("## <font color='green'> samples texts </font>"))

#creating sample text
samples = ["The cat sat on the mat", " The dog ate my homework"] 
samples

## <font color='green'> samples texts </font>

['The cat sat on the mat', ' The dog ate my homework']

In [57]:
display(Markdown("## <font color='green'> word level one hot encoding </font>"))

#initializing word-encoding dictionary
token_index = {} 

def word_one_hot_embeddings(text_samples,max_sentence_length=8):
    """
        # Creating sentence vectors by represent each word as a vector
        # word as a vector: vector of length of vocabulary, with "1" for that specified word and zero elsewhere
    """

    # Encoding words in the corpus
    print("\nStarting to create token_index for every distinct vocabulary")
    for sample in text_samples:
        for word in sample.split():
            if word not in token_index.keys():
                token_index[word] = len(token_index) + 1
    print("token_index created.\n")

    # Word level one hot encoding
    print("\nStarting to create sentence vector using token_index")
    results = np.zeros(shape=(len(text_samples),len(token_index)+1))
    for i , sample in enumerate(text_samples):
        for j , word in enumerate(sample.split()):
            index_ = token_index[word]
            results[i,index_] = 1
    print("sentences vectorised.\n")
    return (results)

word_level_vectorised_sample = word_one_hot_embeddings(text_samples=samples,max_sentence_length=8)
shape = (word_level_vectorised_sample.shape)



display(Markdown("### created word index's for sentence encoding"))
print (token_index)

display(Markdown("### result"))
print("Output shape {}".format(word_level_vectorised_sample.shape))
print("# sample:{},  specified max length:{},  # vocabulary:{}\n".format(len(samples),shape[0],shape[1]))
print(word_level_vectorised_sample)

print(
"""
Note:  In the final result, index of each element in the vectors denotes the eoncoding of the words.
       "0"/"1" denote presence of a vocabulary
"""
)

## <font color='green'> word level one hot encoding </font>


Starting to create token_index for every distinct vocabulary
token_index created.


Starting to create sentence vector using token_index
sentences vectorised.



### created word index's for sentence encoding

{'The': 1, 'cat': 2, 'sat': 3, 'on': 4, 'the': 5, 'mat': 6, 'dog': 7, 'ate': 8, 'my': 9, 'homework': 10}


### result

Output shape (2, 11)
# sample:2,  specified max length:2,  # vocabulary:11

[[0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1.]]

Note:  In the final result, index of each element in the vectors denotes the eoncoding of the words.
       "0"/"1" denote presence of a vocabulary



In [58]:
display(Markdown("## <font color='green'> word level one hot encoding - KERAS </font>"))
# One-hot encoding using keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=len (token_index))
tokenizer.fit_on_texts(samples)

sequences = tokenizer.texts_to_sequences(samples) # sentence encoding
one_hot_results = tokenizer.texts_to_matrix(samples,mode='binary') # creating one hot results
shape = (one_hot_results.shape)

word_index = tokenizer.word_index
one_hot_results

display(Markdown("### sentence encoding results"))
print (sequences)
display(Markdown("### created word index's for sentence encoding"))
print (word_index)



display(Markdown("### result"))
print("Output shape {}".format(one_hot_results.shape))
print("# sample:{},  specified max length:{},  # vocabulary:{}\n".format(len(samples),shape[0],shape[1]))
print (one_hot_results)

print(
"""
Note:  In the final result, index of each element in the vectors denotes the eoncoding of the words.
       "0"/"1" denote presence of a vocabulary
"""
)

## <font color='green'> word level one hot encoding - KERAS </font>

### sentence encoding results

[[1, 2, 3, 4, 1, 5], [1, 6, 7, 8, 9]]


### created word index's for sentence encoding

{'the': 1, 'cat': 2, 'sat': 3, 'on': 4, 'mat': 5, 'dog': 6, 'ate': 7, 'my': 8, 'homework': 9}


### result

Output shape (2, 10)
# sample:2,  specified max length:2,  # vocabulary:10

[[0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 1. 1. 1.]]

Note:  In the final result, index of each element in the vectors denotes the eoncoding of the words.
       "0"/"1" denote presence of a vocabulary



In [59]:
display(Markdown("## <font color='green'> character level one hot encoding </font>"))

def character_one_hot_embeddings(characters,max_sentence_length_in_characters=30):
    """
        # Creating sentence vectors by using character level encoding
    """
    character_index =  dict(zip(characters,(range(1,len(characters)+1))))
    results = np.zeros(shape=(len(samples),max_sentence_length_in_characters,len(characters)+1))

    for i , sample in enumerate(samples):
        #print (sample)
        for j , character in enumerate(sample):
            #print (i,j,character_index.get(character),character)
            results[i,j,character_index.get(character)] = 1
    return (results,character_index)
            
characters = string.printable
char_level_vectorised_sample, character_index = character_one_hot_embeddings(characters)
shape = (char_level_vectorised_sample.shape)

display(Markdown("### characters used for encoding"))
print ("{} distinct character vocab present".format(len(characters)))
print ("Character level indexing")
print(character_index,"\n")


display(Markdown("### result"))
print("Output shape {}".format(char_level_vectorised_sample.shape))
print("# sample:{},  specified max length:{},  # vocabulary:{}\n".format(shape[0],shape[1],shape[2]))
print(char_level_vectorised_sample)

## <font color='green'> character level one hot encoding </font>

### characters used for encoding

100 distinct character vocab present
Character level indexing
{'0': 1, '1': 2, '2': 3, '3': 4, '4': 5, '5': 6, '6': 7, '7': 8, '8': 9, '9': 10, 'a': 11, 'b': 12, 'c': 13, 'd': 14, 'e': 15, 'f': 16, 'g': 17, 'h': 18, 'i': 19, 'j': 20, 'k': 21, 'l': 22, 'm': 23, 'n': 24, 'o': 25, 'p': 26, 'q': 27, 'r': 28, 's': 29, 't': 30, 'u': 31, 'v': 32, 'w': 33, 'x': 34, 'y': 35, 'z': 36, 'A': 37, 'B': 38, 'C': 39, 'D': 40, 'E': 41, 'F': 42, 'G': 43, 'H': 44, 'I': 45, 'J': 46, 'K': 47, 'L': 48, 'M': 49, 'N': 50, 'O': 51, 'P': 52, 'Q': 53, 'R': 54, 'S': 55, 'T': 56, 'U': 57, 'V': 58, 'W': 59, 'X': 60, 'Y': 61, 'Z': 62, '!': 63, '"': 64, '#': 65, '$': 66, '%': 67, '&': 68, "'": 69, '(': 70, ')': 71, '*': 72, '+': 73, ',': 74, '-': 75, '.': 76, '/': 77, ':': 78, ';': 79, '<': 80, '=': 81, '>': 82, '?': 83, '@': 84, '[': 85, '\\': 86, ']': 87, '^': 88, '_': 89, '`': 90, '{': 91, '|': 92, '}': 93, '~': 94, ' ': 95, '\t': 96, '\n': 97, '\r': 98, '\x0b': 99, '\x0c': 100} 



### result

Output shape (2, 30, 101)
# sample:2,  specified max length:30,  # vocabulary:101

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [ ]:
display(Markdown("## <font color='green'> word level one hot encoding using hashing </font>"))
dimensionality = len(token_index)
max_length = 10

results = np.zeros((len(samples),dimensionality))
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index= abs(hash(word)% dimensionality)
        results[i, index] =1
        
display(Markdown("### result"))
results

## <font color='green'> word level one hot encoding using hashing </font>

### result

array([[1., 1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 1., 0.]])

In [ ]:
display(Markdown("## <font color='green'>Understanding word embedding with embedding layer</font>"))
display(Markdown("### imdb dataset preparation"))

# loading the IMDB dataset

# download the dataset from "ai.stanford.edu/~amaas/data/sentiment/" 
# extract the dataset 

imdb_dir = "./aclImdb" # actual path to imdb dataset folder
train_dir = os.path.join(imdb_dir,"train")


# collecting text from each file 
# collecting corresponding text labels
labels = []
texts = []
for label_type in ['neg', 'pos']:
    dir_name = os.path.join(train_dir, label_type)
    for fname in os.listdir(dir_name):
         if fname[-4:] == '.txt':
                f = open(os.path.join(dir_name, fname))
                texts.append(f.read())
                f.close()
                if label_type == 'neg':
                    labels.append(0)
                else:
                    labels.append(1)

print ("Raw data\n")

print ("Raw text {}\n".format(texts[:2]))
print ("text labels {}\n".format(labels[:2]))

display(Markdown("### creating word embedding on imdb dataset"))


# pre-processing initializations
n_vocab = 10000 # max number of distinct vocabulary (top 10,000)
max_sentence_length = 100  # Cuts a review after 100 words
training_samples = 200 # number of training examples
validation_samples = 10000 # number of validation examples

# pre-processing dataset

# starting to create word emdedding

# building tokenizer (keras object that holds index_to_word dictionary, n_vocab, etc parameters)
tokenizer = Tokenizer(num_words=n_vocab)
tokenizer.fit_on_texts(texts) # feeding the text data to tokenizer

# creating word vectors using keras tokenizer & cutting each sentence after 100 words
sequences = tokenizer.texts_to_sequences(texts) 
sequences_padded = pad_sequences(sequences,maxlen=max_sentence_length,
                                padding='post', truncating='post') # default paddind is "pre" in keras
word_index = tokenizer.word_index # word_to_index mappind dictionary

print ("Found {} unique token.\n".format(len(word_index)) )

# training and testind data split
indices = np.arange(sequences_padded.shape[0])
np.random.shuffle(indices)
sequences_padded = sequences_padded[indices]
labels = np.asarray(labels)[indices]
x_train = sequences_padded[:training_samples]
y_train = labels[:training_samples]
x_val = sequences_padded[training_samples: training_samples + validation_samples]
y_val = labels[training_samples: training_samples + validation_samples]

print ("After data preprocessing")
print(" # Training samples {}, # Testing samples {}\n".format(x_train.shape[0],x_val.shape[0]))
print("Word encoded imdb review data")
print(x_train[:2])

print("\nImdb review data lables")
print(y_train[:2])
print(
"""
Note:  
0 : "Negative review"
1 : "Positive review"
"""
)

## <font color='green'>Understanding word embedding with embedding layer</font>

### imdb dataset preparation

Raw data

Raw text ["Working with one of the best Shakespeare sources, this film manages to be creditable to it's source, whilst still appealing to a wider audience.<br /><br />Branagh steals the film from under Fishburne's nose, and there's a talented cast on good form.", 'Well...tremors I, the original started off in 1990 and i found the movie quite enjoyable to watch. however, they proceeded to make tremors II and III. Trust me, those movies started going downhill right after they finished the first one, i mean, ass blasters??? Now, only God himself is capable of answering the question "why in Gods name would they create another one of these dumpster dives of a movie?" Tremors IV cannot be considered a bad movie, in fact it cannot be even considered an epitome of a bad movie, for it lives up to more than that. As i attempted to sit though it, i noticed that my eyes started to bleed, and i hoped profusely that the little girl from the ring would crawl through the TV and kill me. did 

### creating word embedding on imdb dataset

In [ ]:
def plot_model_training_history(history):
    
    #collecting all post-training values 
    acc = history.history['acc']
    val_acc = history.history['val_acc']
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    epochs = range(1, len(acc) + 1)
    
    # ploting losses
    plt.plot(epochs, loss, 'bo', label='Training loss')
    plt.plot(epochs, val_loss, 'b', label='Validation loss')
    plt.title('Training and validation loss')
    plt.legend()
    plt.show()
    
    plt.figure()
    
    # ploting accuracies
    plt.plot(epochs, acc, 'bo', label='Training acc')
    plt.plot(epochs, val_acc, 'b', label='Validation acc')
    plt.title('Training and validation accuracy')
    plt.legend()
    return

In [ ]:
display(Markdown("### building a sequential model using embedding layer"))


# pre-training initializations
max_sentence_length = max_sentence_length  # max sentence length taken from imdb dataset preparation stage

#embedding layer initializations
n_vocab_embedding_layer = n_vocab
size_of_word_vector = 8

## Embedding layer is trainable layer. It is best understood as a dictionary 
## that maps integer indices (which stands for specific words) to a dense vectors

# Creating a 1 layer neural network
model = Sequential()
model.add(Embedding(n_vocab_embedding_layer,size_of_word_vector,input_length=max_sentence_length)) 
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer="rmsprop",loss="binary_crossentropy",metrics=["acc"])
model.summary()

# Starting model training
history = model.fit(x_train,y_train,
                   epochs = 10,
                    batch_size = 32,
                    validation_data=(x_val,y_val)
                   )

# ploting model training results
display(Markdown("### result"))
plot_model_training_history(history)

In [ ]:
display(Markdown("## <font color='green'> Using Glove pre-trained embedding for embedding matrix</font>"))

#loading data from glove embedding to dict
embeddings_index = {}
f = open("./pretrained_embedding_data/glove.6B.100d.txt")
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()
print('Found %s word vectors in pretrained glove embedding.' % len(embeddings_index))

# preparing glove word-embedding matrix
embedding_dim = 100   # word - vector size as taken from glove embedding
word_index = word_index # word_index taken from imdb dataset preparation stage
n_vocab_embedding_layer = n_vocab # max vacabulory size taken from imdb dataset preparation stage
embedding_matrix = np.zeros((n_vocab_embedding_layer, embedding_dim)) # embedding matrix initialization

for word, i in word_index.items(): 
    embedding_vector = embeddings_index.get(word)
    if i < n_vocab_embedding_layer:
        if embedding_vector is not None:
                embedding_matrix[i] = embedding_vector #Words not found in embedding index will be all-zeros.

display(Markdown("### result"))
print("shape of created word-embedding layer : {}\n".format(embedding_matrix.shape))
print("sample representation of encoded words using glove pre-trained embedding")
print(embedding_matrix[2:4])

In [ ]:
display(Markdown("### building a sequential model using glove embeding in embedding layer"))

# pre-processing initializations
max_sentence_length = max_sentence_length  # max sentence length taken from imdb dataset preparation stage

#embedding layer initializations
n_vocab_embedding_layer = n_vocab # max number vocabulary taken from imdb dataset preparation stage
size_of_word_vector = embedding_dim # taken from  embedding matrix creation stage

# creating a 2 layer neural network
model = Sequential()
model.add(Embedding(n_vocab_embedding_layer, size_of_word_vector, input_length=max_sentence_length))
model.add(Flatten())
model.add(Dense(32, activation='relu')) # 1 hidden layer with relu activation
model.add(Dense(1, activation='sigmoid'))
model.summary()

# freezing the weights of embedding layer so that glove embedding are maintained
model.layers[0].set_weights([embedding_matrix])
model.layers[0].trainable = False

# staring model training
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['acc'])
history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_data=(x_val, y_val))

# ploting model training results
display(Markdown("### result"))
plot_model_training_history(history)

In [ ]:
display(Markdown("## <font color='green'> 2 layer network training embedding layer</font>"))

# pre-processing initializations
max_sentence_length = max_sentence_length  # max sentence length taken from imdb dataset preparation stage

#embedding layer initializations
n_vocab_embedding_layer = n_vocab # max number vocabulary taken from imdb dataset preparation stage
size_of_word_vector = embedding_dim # taken from  embedding matrix creation stage


# creating a 2 layer neural network
model = Sequential()
model.add(Embedding(n_vocab_embedding_layer, size_of_word_vector, input_length=max_sentence_length))
model.add(Flatten())
model.add(Dense(32, activation='relu')) # 1 hidden layer with relu activation
model.add(Dense(1, activation='sigmoid'))
model.summary()

## NOTE: No layer freezing

# staring model training
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['acc'])
history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_data=(x_val, y_val))

# ploting model training results
display(Markdown("### result"))
plot_model_training_history(history)